### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by kevquirk** [brpaz/ulauncher-pwgen#1]
When trying to use this extension, it doesn't work. I use "pwgen" and nothing happens. If I change any settings and try to click save, I get the following error:

Unexpected API error. KeyError: com.github.brpaz.ulauncher-pwgen

**Comment by brpaz** [comment]
Hi. Please make sure you have installed the "pwgen" python package. Missing dependencies is the common cause for this error.

Ex:` pip install pwgen`

**Comment by kevquirk** [comment]
Hey,

Apologies for the ridiculous delay in reply - I completely forgot that this issue was still open. Thanks for the quick reply, I wish I could have responded in kind.

Your advice fixed the issue for me in Ubuntu 18.04. For anyone else having the same issue, you need these commands:

`sudo apt install python-pip`
`pip install pwgen`

Log out/in and everything should be working.

Thanks again.

Kev
