### ISSUE TITLE
Every password generate between b'' 

### ISSUE THREAD

**Issue by pedrovillalobos** [brpaz/ulauncher-pwgen#7]
Any size of password I generate it is always shown between b''.

Example:  
pwgen 16  
Returns: b'Wae5rae.f4See1ee'

**Comment by brpaz** [comment]
Ah. That´s related to changes in Python 3 and the way string encoding works. Will try to commit a fix soon,

**Comment by pedrovillalobos** [comment]
@brpaz thats brilliant. .thanks!
